# Site settings
# These are used to personalize your new site.
title: Jeffrey Wedding # your name here
logo: "/images/JeffWedding_HeadShot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  CSCI 496: Senior Portfolio<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer-Science (class of 2024)
  <br /><br />
  <a href="/pdf/Jeffrey_Wedding_Resume_pdf.pdf">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/jeff-wedding-9558492bb/">View My LinkedIn Profile</a>
repository: "jwedding20/jwedding20.github.io"
github_username:  jwedding20 # update with your username

# Build setting
theme: jekyll-theme-minimal

